### PR TITLE
Update webextension-polyfill

### PR DESCRIPTION
**Pull request by ruihildt**

### CODE REVIEW

**Comment by ruihildt** [comment]
Currently, the following test fail:

```
 FAIL  src/components/Location.test.ts
  ● Test suite failed to run

    This script should only be loaded in a browser extension.

      1 | import { useStorageAsync, StorageLikeAsync } from '@vueuse/core';
    > 2 | import { storage } from 'webextension-polyfill';
        | ^
      3 |
      4 | const browserStorageLocal: StorageLikeAsync = {
      5 |   removeItem(key: string) {

      at node_modules/webextension-polyfill/dist/browser-polyfill.js:10:9
      at node_modules/webextension-polyfill/dist/browser-polyfill.js:5:5
      at Object.<anonymous> (node_modules/webextension-polyfill/dist/browser-polyfill.js:13:3)
      at Object.<anonymous> (src/composables/useBrowserStorageLocal.ts:2:1)
      at Object.<anonymous> (src/composables/useHistoricConnections/useHistoricConnections.ts:2:1)
      at Object.<anonymous> (src/components/RecentLocationButtons.vue:13:48)
      at Object.<anonymous> (src/components/LocationTabs.vue:8:51)
      at Object.<anonymous> (src/components/Location.vue:9:42)
      at Object.<anonymous> (src/components/Location.test.ts:4:1)
```

**Comment by ruihildt** [comment]
@hankolsen I don't understand how this test works, can you check it out?
We could also go over it together at some point.

It's not very urgent as there's no critical vulnerabilities currently.

**Comment by hankolsen** [comment]
https://github.com/mozilla/webextension-polyfill/issues/218#issuecomment-584936358

**Comment by ruihildt** [comment]
> This is the exact same issue: [clarkbw/jest-webextension-mock#149](https://github.com/clarkbw/jest-webextension-mock/issues/149)
> 
> [mozilla/webextension-polyfill#218 (comment)](https://github.com/mozilla/webextension-polyfill/issues/218#issuecomment-584936358)

I had found those links, but looking at `jest.config.js`, I don't know how they fit in and how to adapt it here.
Could you please give me a pointer?

**Comment by hankolsen** [comment]
I guess the easiest is to update the `setupFiles` in `jest.config.js` to something like this:
```
 setupFiles: ['jest-webextension-mock', './jest.setup.js']
 ```
 
 And then create a file in the root called `jest.setup.js` with the content
 ```
 chrome.runtime.id = "testid";
```

**Comment by ruihildt** [comment]
Thanks, code is working as intended. :)

**Review by hankolsen — APPROVED** [review]

**Pull request merged**
