### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ruihildt**

### CODE REVIEW

**Comment by ruihildt** [comment]
@hankolsen Can you have a look at the failing test? I can't figure out what's going on.

**Comment by hankolsen** [comment]
It says
`Cannot find module '@babel/preset-env'`

Any changes there?

**Comment by ruihildt** [comment]
> Any changes there?

I'm not sure, Babel was never explicitly installed.

**Comment by hankolsen** [comment]
I'd revert the changes and the redo them one by one, running the tests after each to figure out where it breaks

**Comment by ruihildt** [comment]
> I'd revert the changes and the redo them one by one, running the tests after each to figure out where it breaks

Strangely, the error in the test run by Github and the failure I have locally are different.

Here's what I have locally:

```

**Comment by ruihildt** [comment]
Closed in favor of #135

**Pull request closed without merging**
