### PR TITLE
Fix Leta Search Shortcut/Keyword

### PR DESCRIPTION
**Pull request by celenityy**
The shortcuts for Firefox's included extensions all start with `@`

Ex:

image

Meanwhile, the Leta included in this extension doesn't:

image

This makes the shortcut less convenient to use... it only makes sense we also include the '@' here, which this PR adds.

### CODE REVIEW

**Comment by MrChocolatine** [comment]
Personally I am against this change. It's already boring having to type `@something` so, the fewer letters to type, the better.

**Comment by ruihildt** [comment]
We can probably add both, I don't see any downside to it

**Comment by MrChocolatine** [comment]
Can you let users set their own shortcut?

**Comment by ruihildt** [comment]
> Can you let users set their own shortcut?

Yes, you can always go to `about:preferences#search`, double click on the keyword column and add your own shortcut. (Not really related, but you can also set keyword for individual bookmarks)

**Comment by MrChocolatine** [comment]
Sorry it has been a while, I know we can sometimes set our own shortcut, but sometimes we can't (again, it has been a while).
So that's why I have for keeping `leta`, but if it can be freely customised by users then forget my comment :v: .

**Comment by ruihildt** [comment]
@celenityy I have rewritten history. :/

Would you mind rebasing your changes to the latest main?

**Comment by ruihildt** [comment]
I have actually tried on the current browser, and by default you can use `@` to make `leta` come up, so I don't think we need to do anything here.

[Screencast_20241024_135238.webm](https://github.com/user-attachments/assets/ce499420-c898-4acc-b0e0-7db002556e0f)

**Comment by celenityy** [comment]
@ruihildt You're correct! I just tested on both Mullvad Browser & Firefox with the extension, and it seems to work fine. Not sure if I just missed this (In which cases, I apologize...), or if Mozilla changed something. Thank you for your time and great work on this browser & extension! 🙏

**Pull request closed without merging**
